### PR TITLE
Fix example links

### PR DESCRIPTION
**Pull request by patrick91**
Very excited by this PEP!

I found some broken links on the readme, so I fixed them, hope that's ok!

### CODE REVIEW

**Comment by pauleveritt** [comment]
Very good, thanks Patrick. Is tagstr something you'd like to join in on? Review tutorials, etc.?

**Comment by patrick91** [comment]
@pauleveritt sure! happy to help, just let me know what I should do 😊

**Comment by pauleveritt** [comment]
I am currently digesting the `tutorial.rst` in the root, to overhaul it a bit. Interested to work on that?

**Comment by patrick91** [comment]
@pauleveritt do you want me to review or rewrite it? 😊

**Comment by pauleveritt** [comment]
Let me get a branch going in the next couple of days, we'll refactor it into a multi-step, longer-form tutorial. Sound good?

**Comment by patrick91** [comment]
yup!

**Pull request merged**
